//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinYinHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PinYinHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 adeliyanuo 阿德里亚诺
        ///aerbaniya 阿尔巴尼亚
        ///aerbote 阿尔伯特
        ///aerweisi 阿尔维斯
        ///aganzhengzhuan 阿甘正传
        ///ajimide 阿基米德
        ///alafate 阿拉法特
        ///alibuda 阿里布达
        ///alinasi 阿里纳斯
        ///alisidun 阿里斯顿
        ///aqimeisu 阿奇霉素
        ///asaibaijiang 阿塞拜疆
        ///awashanzhai 阿瓦山寨
        ///ayi 阿姨
        ///ayi 阿伊
        ///ayi 阿忆
        ///ayi 阿依
        ///ayi 阿一
        ///ayi 阿怡
        ///ayo 啊哟
        ///aiai 哎哎
        ///aiaiaiai 唉唉唉唉
        ///aiaiaiai 爱爱爱爱
        ///aiaide 矮矮的
        ///aibanggongjiao 爱帮公交
        ///aibao 爱宝
        ///aibian 挨边
        ///aibudanxing 爱不单行
        ///aibuqi 爱不起
        ///aibuwan 爱不完
        ///aichou 哀愁
        ///aicai 爱财
        ///aicao 艾草
        ///aicheng 爱城
        ///aichi 爱吃
        ///aichiyu 爱吃鱼
        ///aichong 爱宠
        ///aichuan 爱穿
        ///aiciba 爱词霸
        ///aida 爱打
        ///a [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
    }
}
